name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

####      - name: Set up kubectl
####        uses: azure/setup-kubectl@v1
####        with:
####          kubectl-version: 'latest'
####
####      - name: Configure kubectl
####        run: |
####          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
####
####      - name: Apply Kubernetes Manifests
####        run: |
####          kubectl apply -f kubernetes/db-deployment.yaml
####          kubectl apply -f kubernetes/deployment.yaml
####          kubectl apply -f kubernetes/secret.yaml
####
####      - name: Wait for deployment to complete
####        run: |
####          kubectl rollout status deployment/fastapi-heroes